import { NextResponse } from "next/server";
import { z } from "zod";

import { chartPlanSchema, localDashboardPlan, materializeDashboard } from "@/lib/ai-dashboard";

export const runtime = "nodejs";

const analysisSchema = z.object({
  summary: z.object({
    sourceRows: z.number(), usableRows: z.number(), uniqueBaseClaims: z.number(), claimsOver30Days: z.number(),
    over30Rate: z.number(), loopingEvents: z.number(), loopInstances: z.number(), totalInterestAmount: z.number(),
  }),
  loopingEvents: z.array(z.object({ event: z.string(), averageDaysBetween: z.number(), totalDaysBetween: z.number(), loopInstances: z.number(), uniqueBaseClids: z.number() })).max(5000),
  ageBreakdown: z.array(z.object({ bucket: z.enum(["30 days and less", "More than 30 days"]), uniqueBaseClids: z.number(), averageAgeDays: z.number(), totalInterestAmount: z.number(), share: z.number() })).max(2),
  over30Events: z.array(z.object({ event: z.string(), averageDaysBetween: z.number(), totalDaysBetween: z.number(), loopInstances: z.number(), uniqueBaseClids: z.number(), eventCount: z.number() })).max(5000),
});

const requestSchema = z.object({ command: z.string().trim().min(2).max(600), analysis: analysisSchema });

export async function POST(request: Request) {
  try {
    const { command, analysis } = requestSchema.parse(await request.json());
    const apiKey = process.env.OPENAI_API_KEY?.trim();
    if (!apiKey) {
      const plan = localDashboardPlan(command, analysis);
      return NextResponse.json({
        dashboard: materializeDashboard(plan, analysis, "local", "Add OPENAI_API_KEY in Vercel to enable the AI planner. This dashboard was generated by the safe local planner."),
        message: "Dashboard created with the local planner. Add the OpenAI API key to enable open-ended AI chart composition.",
      });
    }

    try {
      const plan = await createOpenAIPlan(command, analysis, apiKey);
      return NextResponse.json({
        dashboard: materializeDashboard(plan, analysis, "openai"),
        message: `AI dashboard created with ${plan.charts.length} visualization${plan.charts.length === 1 ? "" : "s"}.`,
      });
    } catch (error) {
      console.error("AI dashboard planning failed", error);
      const plan = localDashboardPlan(command, analysis);
      return NextResponse.json({
        dashboard: materializeDashboard(plan, analysis, "local", "The AI planner was unavailable, so the safe local planner created this dashboard."),
        message: "The AI planner was unavailable, but a dashboard was still created from the requested focus.",
      });
    }
  } catch (error) {
    const message = error instanceof z.ZodError ? "The dashboard request or analysis payload is invalid." : error instanceof Error ? error.message : "Unable to create dashboard.";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}

async function createOpenAIPlan(command: string, analysis: z.infer<typeof analysisSchema>, apiKey: string) {
  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: process.env.OPENAI_CHART_MODEL?.trim() || "gpt-5.6",
      store: false,
      instructions: [
        "You are a process-mining dashboard planner.",
        "Create a useful dashboard that answers the user's request using only the supplied aggregate sources and supported metrics.",
        "Never output SQL, executable code, formulas, field names outside the enums, or instructions to modify data.",
        "Use summary for portfolio KPIs, looping_events for repeated queues, age_breakdown for <=30 vs >30 claims, and over30_events for aged-claim queue delays.",
        "Prefer bar charts for ranked events, donut charts for age shares, KPI for summary values, and tables when the user asks for detail.",
      ].join(" "),
      input: JSON.stringify({
        request: command,
        available: {
          summary: analysis.summary,
          loopingEventCount: analysis.loopingEvents.length,
          ageBuckets: analysis.ageBreakdown.map(row => row.bucket),
          over30EventCount: analysis.over30Events.length,
        },
      }),
      text: { format: { type: "json_schema", name: "dashboard_plan", strict: true, schema: z.toJSONSchema(chartPlanSchema) } },
    }),
  });
  const body = await response.json() as Record<string, unknown>;
  if (!response.ok) throw new Error(`OpenAI request failed with status ${response.status}.`);
  const outputText = extractOutputText(body);
  if (!outputText) throw new Error("OpenAI returned no dashboard plan.");
  return chartPlanSchema.parse(JSON.parse(outputText));
}

function extractOutputText(body: Record<string, unknown>) {
  const output = Array.isArray(body.output) ? body.output : [];
  for (const item of output) {
    if (!item || typeof item !== "object") continue;
    const content = Array.isArray((item as { content?: unknown }).content) ? (item as { content: unknown[] }).content : [];
    for (const part of content) {
      if (part && typeof part === "object" && (part as { type?: unknown }).type === "output_text" && typeof (part as { text?: unknown }).text === "string") return (part as { text: string }).text;
    }
  }
  return "";
}
